-- MySQL Script generated by MySQL Workbench
-- Sat May 23 19:17:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema курсова
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema курсова
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `курсова` DEFAULT CHARACTER SET utf8 ;
USE `курсова` ;

-- -----------------------------------------------------
-- Table `курсова`.`Teacher 1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `курсова`.`Teacher 1` (
  `idTeacher 1` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `sumame` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTeacher 1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `курсова`.`Student 1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `курсова`.`Student 1` (
  `idStudent 1` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `sumame` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudent 1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `курсова`.`English`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `курсова`.`English` (
  `idEnglish` INT NOT NULL AUTO_INCREMENT,
  `idTeacher1` INT NOT NULL,
  `idStudent1` INT NOT NULL,
  PRIMARY KEY (`idEnglish`),
  INDEX `Teacher1_idx` (`idTeacher1` ASC) VISIBLE,
  INDEX `Student 1_idx` (`idStudent1` ASC) VISIBLE,
  CONSTRAINT `Teacher 1`
    FOREIGN KEY (`idTeacher1`)
    REFERENCES `курсова`.`Teacher 1` (`idTeacher 1`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Student 1`
    FOREIGN KEY (`idStudent1`)
    REFERENCES `курсова`.`Student 1` (`idStudent 1`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `курсова`.`Teacher 2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `курсова`.`Teacher 2` (
  `idTeacher 2` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `sumame` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTeacher 2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `курсова`.`Student 2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `курсова`.`Student 2` (
  `idStudent 2` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sumame` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudent 2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `курсова`.`French`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `курсова`.`French` (
  `idFrench` INT NOT NULL,
  `idTeacher 2` INT NOT NULL,
  `idStudent 2` INT NOT NULL,
  PRIMARY KEY (`idFrench`),
  INDEX `Teacher 2_idx` (`idTeacher 2` ASC) VISIBLE,
  INDEX `St_idx` (`idStudent 2` ASC) VISIBLE,
  CONSTRAINT `Teacher 2`
    FOREIGN KEY (`idTeacher 2`)
    REFERENCES `курсова`.`Teacher 2` (`idTeacher 2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `St`
    FOREIGN KEY (`idStudent 2`)
    REFERENCES `курсова`.`Student 2` (`idStudent 2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
